[tool.poetry]
name = "container-backups"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.35.91"
pydantic-settings = "^2.7.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
ruff = "^0.9.0"
pytest = "^8.3.4"
testcontainers = "^4.9.0"
minio = "^7.2.13"
types-boto3 = "^1.35.96"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
s3_backup = "container_backups.s3_backup:main"
