[tool.poetry]
name = "container-backups"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.34.149"
pydantic-settings = "^2.4.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.11.1"
ruff = "^0.5.6"
pytest = "^8.3.2"
testcontainers = "^4.7.2"
minio = "^7.2.7"
types-boto3 = "^1.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
s3_backup = "container_backups.s3_backup:main"
